### ISSUE TITLE
Recipe fails if BaseVersion is N/A

### ISSUE THREAD

**Issue by tcinbis** [mosen/ccp-recipes#16]
I tried running the Example recipe for Acrobat DC munki and I got following error output:
`The following recipes failed:
    AcrobatDC.munki.recipe
        Error in local.munki.Adobe.AcrobatDC: Processor: CreativeCloudFeed: Error: No package matched the SAP code (APRO), base version (15.0), and version (15.0) combination you specified.`

Then I tried changing it to "N/A" and got still the same error message:
`The following recipes failed:
    AcrobatDC.munki.recipe
        Error in local.munki.Adobe.AcrobatDC: Processor: CreativeCloudFeed: Error: No package matched the SAP code (APRO), base version (N/A), and version (15.0) combination you specified.`

**Comment by tcinbis** [comment]
Seems to work, if you do not set a BaseVersion. Is this the supposed behaviour?

**Comment by mosen** [comment]
At the moment this is the case: acrobat is one of a few products which do not have a baseversion

Valid version combinations are usually:
Baseversion plus version=latest
Or
No baseversion and exact version

**Comment by timsutton** [comment]
Just my 2c on packaging Acrobat Pro DC with CCP:

Acrobat Pro packages have always been awkwardly shoehorned into the CS/CC packaging tools, and so very few rules and patterns used by these recipes and general "Adobe CC deployment" workflows apply. The `ccp-recipes`'s existing support for detecting existing CCP builds (to avoid unneeded rebuilds) will also not work, partly because Adobe puts no helpful version metadata in the feed, and it is mostly buried in the packages themselves.

It would probably be necessary to special-case Acrobat support or split it out into its own recipe, at least for the Munki recipe.

Adobe's made it possible to deploy Acrobat Pro using an available download here, and customize it with the customizer wizard:

https://helpx.adobe.com/acrobat/kb/acrobat-dc-downloads.html

Because of all the added baggage (and hundreds of MB of installer code) that CCP brings with it, and that it "obfuscates" to the admin that it's not actually using any of the CS installer tooling, I continue to recommend to anyone who asks to just use their existing supported "bare" package and leave Acrobat Pro DC far away from CCP.

The only catch here is that I'm not sure this download is accessible to anyone besides enterprise customers. And I suppose that if you're using a deployment model of always including a serial license, that this is less helpful.

I have a not-fully-fleshed-out script which I've been using for quite a while to automate the client customization wizard part of things, which at some point I'd like to turn into its own recipe, but for anyone interested:

https://gist.github.com/timsutton/212bfed9da2056a070a12ac27febeb71

**Comment by mosen** [comment]
I don't have a problem with that setup because as you said acrobat is the extreme outlier in this case. I don't know what the implications are for teams licenses

**Comment by macmule** [comment]
Should have been fixed as of: https://github.com/mosen/ccp-recipes/pull/21

**Comment by timsutton** [comment]
This issue was moved to autopkg/adobe-ccp-recipes#2
