### ISSUE TITLE
WARNING: pkginfo for 'AdobeAcrobatProDCCC2017' contains no installation check info!

### ISSUE THREAD

**Issue by macmule** [mosen/ccp-recipes#19]
> MunkiImporter: WARNING: pkginfo for 'AdobeAcrobatProDCCC2017' contains no installation check info!
MunkiImporter:     No useful receipts were detected, and no 'installs' items were provided.
MunkiImporter:     If you do not add an 'installs' item or an installcheck_script,
MunkiImporter:     Munki will have no way to determine the item's installation state.
MunkiImporter:     This can result in repeated installation attempts or failure to attempt
MunkiImporter:     installation at all.

Added APRO (Acrobat Pro DC) to an override for the CreativeCloudApp.munki.recipe.

Bug me on Slack so we can figure this out :)

**Comment by macmule** [comment]
https://github.com/mosen/ccp-recipes/issues/16#issuecomment-291153605

**Comment by timsutton** [comment]
I'm still of two minds of this:

One is that `APRO` shouldn't be supported by these recipes, or at least not _yet_, and they should fail if `APRO` is the requested package. Acrobat Pro gets a quarterly update for the "full" installer, and you're still left to fend for yourself to get the patches anyway. Given that this repo enables building a over a dozen other regularly-updated apps, it seems like a lot of extra work to do the special casing required to extract additional info and _only if_ APRO is the main application packaged. It means we'd probably have to make it so that to package APRO, you'd have to override a different recipe than all the others.

There's a cleaner way to way to deploy it as I [described here](https://github.com/mosen/ccp-recipes/issues/16#issuecomment-291153605), but so far nobody's posted any public AutoPkg recipes to do that yet. Still I feel like it's the right thing to do when there seems to be a cleaner way that doesn't involve unnecessarily wrapping all of Adobe's CCP-related packaging around Acrobat Pro.

The other opinion is that it might be worth still supporting these via a separate recipe given that there will be a number of users who are building _all_ their packages as device- or serial-licensed, and so it just makes sense from a workflow perspective to do the same for Acrobat. Using AutoPkg processors it would also be possible to extract a proper `version` from the app bundle rather than the one made available in the Creative Cloud feed.

However, for this to work, it would need a way to know when there's a new version because all the feed shows is `15` (or maybe now `17`), but the version within will change from time to time. That logic happens by checking parameters passed to the automation XML, so that would _also_ need special-case code.

**Comment by macmule** [comment]
Adobe Gaming SDK same errors... I'll plough on, see if any others have the same

**Comment by macmule** [comment]
H/T to @mosen.

```
<key>parse_proxy_xml</key>
<true/>
```

Adding the above to the Acrobat override worked

**Comment by macmule** [comment]
Ignore me.. I was wrong

**Comment by macmule** [comment]
Fixed as of: https://github.com/mosen/ccp-recipes/pull/21
