### ISSUE TITLE
Munki recipe fails if CCP build hasn't changed

### ISSUE THREAD

**Issue by chelming** [mosen/ccp-recipes#5]
If the CCP build hasn't changed, i.e., returns `CreativeCloudPackager: Skipping CCP build: version has not changed.`, the Munki build will fail because `%uninstaller_pkg_path%` isn't returned as an output variable.

```
CreativeCloudPackager: Skipping CCP build: version has not changed.
{'Output': {}}
DmgCreator
{'Input': {'dmg_path': u'/Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015_Install-10.4.0.dmg',
           'dmg_root': u'/Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015'}}
DmgCreator: Created dmg from /Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015 at /Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015_Install-10.4.0.dmg
{'Output': {}}
DmgCreator
Use of undefined key in variable substitution: u'uninstaller_pkg_path'
{'Input': {'dmg_path': u'/Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015_Uninstall-10.4.0.dmg',
           'dmg_root': u'%uninstaller_pkg_path%'}}
creation of /Users/test/Library/AutoPkg/Cache/local.munki.PremiereProCC2015/PremiereProCC2015_Uninstall-10.4.0.dmg failed: hdiutil: create failed - No such file or directory

Failed.
```

**Comment by mosen** [comment]
Will revert the commit for the moment and test on another branch.

**Comment by chelming** [comment]
Would a `StopProcessingIf` processor at the end of the pkg recipe fix that? Something to basically tell the Munki recipe that it doesn't need to run.

**Comment by mosen** [comment]
I'll have to get more clarity from @timsutton on the behaviour he wanted. A build should already be aborted if the inputs are the same as a previous build.

**Comment by timsutton** [comment]
That's right, the pkg build is already skipped if it detects an existing package with the same input "manifest." But `uninstaller_pkg_path` was still being set, so I think mosen's change was exiting the processor too early.

I think @mosen's got the general idea of what I was pitching with #4, but it may be over-eager in assuming a download had changed. And even if it did, it's still true that we would need to make sure that those output variables would get set, or be able to set them explicitly in the recipe so that we don't rely on them being set by a processor.

I think originally I tried using them explicitly in the recipe and changed to defining them in the processor, potentially so that other child recipes could make use of the path or so that it was less unwieldy. If we need to move an output variable "up a step" into a different processor that's probably fine too.

**Comment by chelming** [comment]
Should this be closed now?

**Comment by timsutton** [comment]
I've definitely run more than a fair share of runs with Munki import steps where no build had changed, so yes, it seems to be resolved.
